### ISSUE TITLE
compare_areas(): scale_fill name in labs()

### ISSUE THREAD

**Issue by cucumberry** [PublicHealthEngland/fingertipscharts#16]
`compare_areas()` hard-codes the fill legend title as "Area compared to Benchmark":

https://github.com/PublicHealthEngland/fingertipscharts/blob/master/R/quick_charts.R#L137

I'd prefer to have it say "Area compared to England". Because the name is defined within `scale_fill_phe()`, you can't overwrite it without replacing the whole scale. If it were defined in `labs()` instead, that wouldn't be a problem. For example:

```r
        if (!missing(fill)) {
                fill <- enquo(fill)
                compare_areas <- compare_areas +
                        geom_col(aes_string(fill = quo_text(fill))) +
                        scale_fill_phe(theme = "fingertips") +
                        labs(fill = "Area compared to Benchmark")
        }
```

I've noticed names defined in the scale functions elsewhere too, which could probably all be moved into `labs()`, but it's only been a problem for me with `compare_areas()`.

**Comment by sebastian-fox** [comment]
Hi @cucumberry - thanks for reporting this. I've updated the package for both this function and the `map` function. they are available in the dev version of the package. If you're happy with the changes, please could you close this issue? 
```
devtools::install_github("PublicHealthEngland/fingertipscharts",
                         build_vignettes = TRUE)
```

**Comment by sebastian-fox** [comment]
ps: I didn't realise you could name legends in the `labs()` function - thanks for the tip

**Comment by cucumberry** [comment]
Thanks Seb, yes it seems to work right
