### ISSUE TITLE
Create github pages site for fingertips charts

### ISSUE THREAD

**Issue by simonthelwall** [publichealthengland/fingertipscharts#19]
## Problem statement
CRAN documentation is ugly, pkgdown sites are beautiful. 

## Suggested solution
Create a pkgdown site and host on publichealthengland.gitihub.io/fingertipscharts

**Comment by simonthelwall** [comment]
I'm happy to do this, so feel free to put me as the assignee.

**Comment by sebastian-fox** [comment]
Thanks @simonthelwall - good idea

**Comment by sebastian-fox** [comment]
Fixed in 8f4aedd823c2e59d3e75716ce8b0175bcc009d63

**Comment by simonthelwall** [comment]
@sebastian-fox I think you may need to make some changes to the repository settings for this to take effect:
[help pages here](https://help.github.com/en/enterprise/2.13/user/articles/configuring-a-publishing-source-for-github-pages)

I couldn't find anything at [publichealthengland.github.io/fingertipscharts](http://publichealthengland.github.io/fingertipscharts) but would expect to if this had been successful.
