### ISSUE TITLE
pretty_breaks is retired

### ISSUE THREAD

**Issue by simonthelwall** [PublicHealthEngland/fingertipscharts#20]
## Problem statement
'population()' function uses `scales::pretty_breaks()` (right?). This is retired:

> pretty_breaks() is retired; use breaks_pretty() instead.

## Suggested solution
Use `breaks_pretty()` instead

**Comment by sebastian-fox** [comment]
This is confusing. I'll change to `breaks_pretty()`.

**Comment by simonthelwall** [comment]
I've got no idea what the difference is, but that's what the message says .
