### ISSUE TITLE
Header position on spine charts

### ISSUE THREAD

**Issue by AndyELich** [PublicHealthEngland/fingertipscharts#5]
Position of Best / Highest column either truncates header text or overlaps bars on spine chart
![spine header position issue](https://user-images.githubusercontent.com/10868160/51914643-3f617780-23d1-11e9-84c1-05620672d7fa.png)

**Comment by sebastian-fox** [comment]
This is done in v0.0.4 a8e9b6c10964808a2d07d33d1695f19ccda7be71

**Comment by sebastian-fox** [comment]
This is done in v0.0.4 a8e9b6c10964808a2d07d33d1695f19ccda7be71
