### ISSUE TITLE
Change dp display for individual indicators in Spine Charts

### ISSUE THREAD

**Issue by JoannaWatson** [PublicHealthEngland/fingertipscharts#7]
It would be good to be able to change the number of decimal places an indicator's value defaults to - currently set at 1 dp but for some indicators (but not all) and those with a small value/range it would be useful to be able to increase this (avoid the possibility of England appearing due to rounding to have the same value as a signficantly higher or lower area value)

**Comment by sebastian-fox** [comment]
This is fixed in v0.0.5
