### ISSUE TITLE
Ordering of domains in spine chart/area profile

### ISSUE THREAD

**Issue by JoannaWatson** [PublicHealthEngland/fingertipscharts#8]
Is it possible to specify a domain order? Currently the area profile defaults to alphabetical order. The only way I have found round this is to give my domain names an alphabetical prefix e.g. 'A. General Health, B. Alcohol/drug misuse' etc not terribly neat!

**Comment by sebsfox** [comment]
Hi @JoannaWatson - I think I follow. Are you including a `domain` argument within your `area_profiles()` function? Like in the Local Authority Health Profiles? To produce these, there is an `indicator_order()` function in `fingertipsR` which allows the user to order the indicators in the same order as is displayed on the website. The domains are therefore in the same order. 

To order the indicators in another way you need to reorder the factor levels for the `indicator` field so it is in the order you want. Happy to discuss more if this doesn't make sense...

**Comment by JoannaWatson** [comment]
Ah that does make sense and thanks for clarifying
